services:
  - type: web
    name: schoolkit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 